Fix clippy issue due to Rust 1.76 update
This fixes the following error:

error: in a `match` scrutinee, avoid complex blocks or closures with blocks;
instead, move the block or closure higher and bind it with a `let`
   --> vendor/google/display_safety/service/vehicledata/generated/har/...
   ...vehicledata/harry_vehicle_data_subscriber/...
   ...harry_vehicle_data_subscriber.rs:109:37
    |
109 |           match builder.spawn(move || {
    |  _____________________________________^
110 | |             Self::poll_subscriptions(subscriptions, callbacks);
111 | |         }) {
    | |_________^
    |

Bug: 328738288
Change-Id: Ib63e7d0b934b308193ee0fd8e9e5db01147edf56